app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("api/", include("ajax.urls", namespace="api")),
    path("api/user/", include("user.urls", namespace="user")),
]

main/urls.py
from django.urls import path

from main.views import (
    CreateCyclingTrainingView,
    CreateDishView,
    CreateJoggingView,
    CreateMealView,
    CreatePowerTrainingView,
    CreateSwimmingView,
    CreateUserView,
    CreateWalkingView,
    CyclingTrainingListView,
    DishListView,
    ExerciseCreateView,
    ExercisesListView,
    ExerciseUpdateView,
    HomePageView,
    JoggingTrainingListView,
    LoginUserView,
    MealListView,
    PowerTrainingsListView,
    SwimmingTrainingListView,
    UpdateCyclingTrainingView,
    UpdateDishView,
    UpdateJoggingView,
    UpdateMealView,
    UpdatePowerTrainingView,
    UpdateSwimmingView,
    UpdateWalkingView,
    UserProfileView,
    WalkingTrainingListView,
    logout_view,
)


urlpatterns = [
    path(
        "",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "home/",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "power-trainings/",
        PowerTrainingsListView.as_view(),
        name="power-trainings-list",
    ),
    path(
        "power-trainings/create",
        CreatePowerTrainingView.as_view(),
        name="create-power-training",
    ),
    path(
        "account/registration",
        CreateUserView.as_view(),
        name="registration"
    ),
    path(
        "accounts/login",
        LoginUserView.as_view(),
        name="login"
    ),
    path(
        "accounts/logout",
        logout_view,
        name="logout"
    ),
    path(
        "accounts/user-profile",
        UserProfileView.as_view(),
        name="user-profile"
    ),
    path(
        "exercises/",
        ExercisesListView.as_view(),
        name="exercises-list"
    ),
    path(
        "exercise/<int:pk>",
        ExerciseUpdateView.as_view(),
        name="exercise-update"
    ),
    path(
        "exercises/create/",
        ExerciseCreateView.as_view(),
        name="create-exercise"
    ),
    path(
        "power-trainings/update/<int:pk>",
        UpdatePowerTrainingView.as_view(),
        name="update-power-training",
    ),
    path(
        "cycling-trainings/",
        CyclingTrainingListView.as_view(),
        name="cycling-training-list",
    ),
    path(
        "cycling-trainings/create",
        CreateCyclingTrainingView.as_view(),
        name="create-cycling-training",
    ),
    path(
        "cycling-trainings/update/<int:pk>",
        UpdateCyclingTrainingView.as_view(),
        name="update-cycling-training",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create",
        CreateDishView.as_view(),
        name="create-dish"
    ),
    path(
        "dishes/update/<int:pk>",
        UpdateDishView.as_view(),
        name="update-dish"
    ),
    path(
        "swimming-trainings/",
        SwimmingTrainingListView.as_view(),
        name="swimming-training-list",
    ),
    path(
        "walking-trainings/",
        WalkingTrainingListView.as_view(),
        name="walking-training-list",
    ),
    path(
        "jogging-trainings/",
        JoggingTrainingListView.as_view(),
        name="jogging-training-list",
    ),
    path(
        "swimming-trainings/create",
        CreateSwimmingView.as_view(),
        name="create-swimming-training",
    ),
    path(
        "walking-trainings/create",
        CreateWalkingView.as_view(),
        name="create-walking-training",
    ),
    path(
        "jogging-traings/create",
        CreateJoggingView.as_view(),
        name="create-jogging-training",
    ),
    path(
        "swimming-trainings/update/<int:pk>",
        UpdateSwimmingView.as_view(),
        name="update-swimming-training",
    ),
    path(
        "jogging-traings/update/<int:pk>",
        UpdateJoggingView.as_view(),
        name="update-jogging-training",
    ),
    path(
        "walking-trainings/update/<int:pk>",
        UpdateWalkingView.as_view(),
        name="update-walking-training",
    ),
    path(
        "meals/",
        MealListView.as_view(),
        name="meal-list"
    ),
    path(
        "meals/create",
        CreateMealView.as_view(),
        name="create-meal"
    ),
    path(
        "meals/update/<int:pk>",
        UpdateMealView.as_view(),
        name="update-meal"
    ),
]

app_name = "main"

templates/main/trainings/power-training/create-power-training.html
{% extends "base_training_form.html" %}

templates/main/trainings/power-training/power-trainings-list.html
{% extends "base_training_list.html" %}
{% block title %}Power trainings{% endblock %}
{% block create_url %}{% url "main:create-power-training" %}{% endblock %}
{% block trainings %}
  {% for power_training in powertraining_list %}
    <a href="{% url "main:update-power-training" power_training.id %}"
       data-training-id="{{ power_training.id }}"
       data-training-type="PW"
       class="training-element col-lg-4">
      <div class="alert alert-primary fade show ">
        <div class="d-flex justify-content-between">
            <span>
               {{ power_training }}
           </span>
          <i class="fa-solid fa-xmark delete-element-icon delete-training-icon"></i>
        </div>
      </div>
    </a>
  {% empty %}
    <h6 class="card-title">
      No trainings yet
    </h6>
  {% endfor %}
{% endblock %}

templates/main/trainings/power-training/update-power-training.html
{% extends "base.html" %}
{% block content %}
  <div class="pagetitle">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url "main:power-trainings-list" %}">Power trainings list</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Update</a>
        </li>
      </ol>
    </nav>
  </div>
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body pt3">
            <div class="row">
              <form method="post">
                {% csrf_token %}
                <h5 class="card-title">
                  Update training
                </h5>
                <div class="row mb-3">
                  <label for="inputStartDate" class="col-md-4 col-lg-4 col-form-label text-center">
                    Start date
                  </label>
                  <div class="col-md-8 col-lg-8">
                    <input type="datetime-local"
                           id="inputStartDate"
                           name="start"
                           class="form-control"
                           value="{{ object.start|date:"Y-m-d" }}T{{ object.start|time:"G:i" }}">
                  </div>

                </div>
                <div class="row mb-3">
                  <label for="inputEndDate" class="col-md-4 col-lg-4 col-form-label text-center">
                    End date
                  </label>
                  <div class="col-md-8 col-lg-8">
                    <input type="datetime-local"
                           id="inputEndDate"
                           name="end"
                           class="form-control"
                           value="{{ object.end|date:"Y-m-d" }}T{{ object.end|time:"G:i" }}">
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="addDescription" class="col-md-4 col-lg-4 col-form-label text-center">
                    Description
                  </label>
                  <div class="col-md-11 col-lg-11 justify-content-center">
                    <textarea class="form-control" id="addDescription" name="description">{{ powertraining.description }}</textarea>
                  </div>

                </div>
                <div class="text-center">
                  <input type="submit" class="btn btn-success">
                </div>
                <input type="hidden" value="{{ user.id }}" name="user">
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body gap-3" id="card_update_power_training">
            <div class="card-title-container mb-3">
              <h5 class="card-title">
                Exercises
              </h5>
              <div class="card-title-container gap-3">
                <select class="form-select" id="select_exercise">
                  {% for exercise in exercises %}
                    <option value="{{ exercise.id }}">{{ exercise.name }}</option>
                  {% empty %}
                    <option value="-1">No exercises yet</option>
                  {% endfor %}
                </select>
                <i class="fa-solid fa-plus create-icon" id="addExercise"></i>
              </div>
            </div>
            <div id="exercise-container">
              {% for exercise in powertraining.exercises.all %}
                <div data-exercise-id="{{ exercise.id }}">
                  <div class="card-title-container mb-3">
                    <div class="d-flex gap-3">
                        <span>
                          {{ exercise.exercise.name }}
                        </span>
                        <i class="fa-solid fa-plus addApproach create-icon"></i>
                      </div>

                    <div class="card-title-container gap-2">
                      <i class="fa-solid fa-xmark delete-element-icon delete-exercise"></i>
                    </div>
                  </div>
                  <ul class="list-group mb-3" style="margin-left: 40px">
                    {% for approach in exercise.approaches.all %}
                      <li class="list-group-item" data-approach-id="{{ approach.id }}">
                        <div class="d-flex">
                          <div class="card-title-container gap-2 justify-content-between">
                            <span>Weight</span>
                            <input type="number"
                                   class="form-control"
                                   name="weight"
                                   value="{{ approach.weight }}"/>
                            <span>Repeats</span>
                            <input type="number"
                                   class="form-control"
                                   name="repeats"
                                   value="{{ approach.repeats }}"/>
                            <button class="btn btn-primary saveApproach">Update</button>
                            <i class="bi bi-x-circle-fill deleteApproach deleteIcon"></i>
                          </div>
                        </div>

                      </li>
                    {% endfor %}
                  </ul>
                </div>
              {% empty %}
                <h6 class="card-title" id="no-exercises-message">
                  No exercises yet
                </h6>
              {% endfor %}
            </div>
            <input type="hidden" value="{{ powertraining.id }}" id="training_id">
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}