app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("api/", include("ajax.urls", namespace="api")),
    path("api/user/", include("user.urls", namespace="user")),
]

main/urls.py
from django.urls import path

from main.views import (
    CreateCyclingTrainingView,
    CreateDishView,
    CreateJoggingView,
    CreateMealView,
    CreatePowerTrainingView,
    CreateSwimmingView,
    CreateUserView,
    CreateWalkingView,
    CyclingTrainingListView,
    DishListView,
    ExerciseCreateView,
    ExercisesListView,
    ExerciseUpdateView,
    HomePageView,
    JoggingTrainingListView,
    LoginUserView,
    MealListView,
    PowerTrainingsListView,
    SwimmingTrainingListView,
    UpdateCyclingTrainingView,
    UpdateDishView,
    UpdateJoggingView,
    UpdateMealView,
    UpdatePowerTrainingView,
    UpdateSwimmingView,
    UpdateWalkingView,
    UserProfileView,
    WalkingTrainingListView,
    logout_view,
)


urlpatterns = [
    path(
        "",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "home/",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "power-trainings/",
        PowerTrainingsListView.as_view(),
        name="power-trainings-list",
    ),
    path(
        "power-trainings/create",
        CreatePowerTrainingView.as_view(),
        name="create-power-training",
    ),
    path(
        "account/registration",
        CreateUserView.as_view(),
        name="registration"
    ),
    path(
        "accounts/login",
        LoginUserView.as_view(),
        name="login"
    ),
    path(
        "accounts/logout",
        logout_view,
        name="logout"
    ),
    path(
        "accounts/user-profile",
        UserProfileView.as_view(),
        name="user-profile"
    ),
    path(
        "exercises/",
        ExercisesListView.as_view(),
        name="exercises-list"
    ),
    path(
        "exercise/<int:pk>",
        ExerciseUpdateView.as_view(),
        name="exercise-update"
    ),
    path(
        "exercises/create/",
        ExerciseCreateView.as_view(),
        name="create-exercise"
    ),
    path(
        "power-trainings/update/<int:pk>",
        UpdatePowerTrainingView.as_view(),
        name="update-power-training",
    ),
    path(
        "cycling-trainings/",
        CyclingTrainingListView.as_view(),
        name="cycling-training-list",
    ),
    path(
        "cycling-trainings/create",
        CreateCyclingTrainingView.as_view(),
        name="create-cycling-training",
    ),
    path(
        "cycling-trainings/update/<int:pk>",
        UpdateCyclingTrainingView.as_view(),
        name="update-cycling-training",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create",
        CreateDishView.as_view(),
        name="create-dish"
    ),
    path(
        "dishes/update/<int:pk>",
        UpdateDishView.as_view(),
        name="update-dish"
    ),
    path(
        "swimming-trainings/",
        SwimmingTrainingListView.as_view(),
        name="swimming-training-list",
    ),
    path(
        "walking-trainings/",
        WalkingTrainingListView.as_view(),
        name="walking-training-list",
    ),
    path(
        "jogging-trainings/",
        JoggingTrainingListView.as_view(),
        name="jogging-training-list",
    ),
    path(
        "swimming-trainings/create",
        CreateSwimmingView.as_view(),
        name="create-swimming-training",
    ),
    path(
        "walking-trainings/create",
        CreateWalkingView.as_view(),
        name="create-walking-training",
    ),
    path(
        "jogging-traings/create",
        CreateJoggingView.as_view(),
        name="create-jogging-training",
    ),
    path(
        "swimming-trainings/update/<int:pk>",
        UpdateSwimmingView.as_view(),
        name="update-swimming-training",
    ),
    path(
        "jogging-traings/update/<int:pk>",
        UpdateJoggingView.as_view(),
        name="update-jogging-training",
    ),
    path(
        "walking-trainings/update/<int:pk>",
        UpdateWalkingView.as_view(),
        name="update-walking-training",
    ),
    path(
        "meals/",
        MealListView.as_view(),
        name="meal-list"
    ),
    path(
        "meals/create",
        CreateMealView.as_view(),
        name="create-meal"
    ),
    path(
        "meals/update/<int:pk>",
        UpdateMealView.as_view(),
        name="update-meal"
    ),
]

app_name = "main"

main/models.py
from datetime import timedelta
from typing import Type

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import (
    CheckConstraint,
    ForeignKey,
    Q,
    UniqueConstraint,
)
from django.utils import timezone
from django.db.models import ExpressionWrapper
from django.db.models import F
from django.db.models import FloatField
from django.db.models import Sum


def convert_datetime_to_string(value) -> str:
    now = timezone.now()
    if value.date() == (now - timedelta(days=1)).date():
        return f"Yesterday, {value.strftime('%H:%M')}"
    elif value.date() == now.date():
        return f"Today, {value.strftime('%H:%M')}"
    else:
        return value.strftime("%d/%m/%Y %H:%M")


class User(AbstractUser):
    SEX_CHOICES = (
        (
            "F",
            "Female",
        ),
        (
            "M",
            "Male",
        ),
        (
            "U",
            "Unsure",
        ),
    )
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, null=True)
    birth_date = models.DateField(
        null=True,
    )
    weight = models.FloatField(
        null=True, validators=[MinValueValidator(20), MaxValueValidator(400)]
    )
    height = models.IntegerField(
        null=True, validators=[MinValueValidator(140), MaxValueValidator(250)]
    )

    @property
    def body_mass_index(self) -> float | None:
        if not self.weight or not self.height:
            return None
        return round((self.weight / (self.height**2)) * 10000, 1)


class Training(models.Model):
    user = ForeignKey(get_user_model(), on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    description = models.TextField(blank=True)

    class Meta:
        abstract = True
        ordering = ["-start"]
        constraints = [
            CheckConstraint(
                check=Q(start__lt=models.F("end")),
                name="%(app_label)s_%(class)s_end_date_grater_than_start_date",
            ),
        ]

    def __str__(self):
        return convert_datetime_to_string(self.start)


class Approach(models.Model):
    weight = models.FloatField(default=0, validators=[MinValueValidator(0)])
    repeats = models.IntegerField(validators=[MinValueValidator(1)])
    training = models.ForeignKey(
        "PowerTrainingExercise",
        on_delete=models.CASCADE,
        related_name="approaches"
    )


class Exercise(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="exercises"
    )
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name


class PowerTrainingExercise(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    power_training = models.ForeignKey(
        "PowerTraining", related_name="exercises", on_delete=models.CASCADE
    )

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=["exercise", "power_training"],
                name="unique_power_training_exercise",
            ),
        ]


class PowerTraining(Training):
    pass


class DistanceAverageSpeedMixin(models.Model):
    average_speed = models.FloatField(validators=[MinValueValidator(1)])
    distance = models.FloatField(validators=[MinValueValidator(1)])

    class Meta:
        abstract = True


class Cycling(Training, DistanceAverageSpeedMixin):
    climb = models.FloatField(validators=[MinValueValidator(1)])


class Swimming(Training, DistanceAverageSpeedMixin):
    pass


class Walking(Training, DistanceAverageSpeedMixin):
    pass


class Jogging(Training, DistanceAverageSpeedMixin):
    pass


class Dish(models.Model):
    name = models.CharField(max_length=255)
    calories = models.FloatField(validators=[MinValueValidator(0.1)])
    protein = models.FloatField(validators=[MinValueValidator(0.1)])
    carbohydrates = models.FloatField(validators=[MinValueValidator(0.1)])
    fats = models.FloatField(validators=[MinValueValidator(0.1)])
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="dishes"
    )

    class Meta:
        ordering = ["name"]
        constraints = [
            UniqueConstraint(
                fields=["user", "name"],
                name="unique_dish_name_for_user"
            )
        ]

    def __str__(self):
        return self.name

    @staticmethod
    def validate_name(
        user: settings.AUTH_USER_MODEL,
        name: str,
        error_type: Type[Exception]
    ) -> None:
        if user.dishes.filter(name__iexact=name).exists():
            raise error_type("Dish with this name already exists")


class DishCount(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    meal = models.ForeignKey(
        "Meal",
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    weight = models.IntegerField(validators=[MinValueValidator(1)])

    class Meta:
        constraints = [
            UniqueConstraint(fields=["dish", "meal"],
                             name="unique_dish_for_meal"),
        ]

    @property
    def calories(self) -> float:
        return round(self.dish.calories * (self.weight / 100), 1)

    @property
    def fats(self) -> float:
        return round(self.dish.fats * (self.weight / 100), 1)

    @property
    def carbohydrates(self) -> float:
        return round(self.dish.carbohydrates * (self.weight / 100), 1)

    @property
    def protein(self) -> float:
        return round(self.dish.protein * (self.weight / 100), 1)


class Meal(models.Model):
    date = models.DateTimeField()
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="meals"
    )

    class Meta:
        ordering = ["-date"]

    @property
    def calories(self):
        return self.dishes.annotate(
            calories=ExpressionWrapper(
                F("dish__calories") * F("weight") / 100,
                output_field=FloatField()
            )
        ).aggregate(total_calories=Sum("calories", default=0))["total_calories"]

    @property
    def fats(self):
        return self.dishes.annotate(
            fats=ExpressionWrapper(
                F("dish__fats") * F("weight") / 100,
                output_field=FloatField()
            )
        ).aggregate(total_fats=Sum("fats", default=0))["total_fats"]

    @property
    def protein(self):
        return self.dishes.annotate(
            protein=ExpressionWrapper(
                F("dish__protein") * F("weight") / 100,
                output_field=FloatField()
            )
        ).aggregate(total_protein=Sum("protein", default=0))["total_protein"]

    @property
    def carbohydrates(self):
        return self.dishes.annotate(
            carbohydrates=ExpressionWrapper(
                F("dish__carbohydrates") * F("weight") / 100,
                output_field=FloatField()
            )
        ).aggregate(
            total_carbohydrates=Sum("carbohydrates", default=0)
        )["total_carbohydrates"]

    def __str__(self):
        return convert_datetime_to_string(self.date)

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import ModelForm
from django.utils import timezone

from main.models import (
    Cycling,
    Dish,
    Exercise,
    Jogging,
    Meal,
    PowerTraining,
    Swimming,
    User,
    Walking,
)


class BaseTrainingForm(ModelForm):
    class Meta:
        fields = [
            "start",
            "end",
            "description",
        ]

    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get("start", None)
        end = cleaned_data.get("end", None)
        if not start:
            return cleaned_data
        if timezone.is_naive(start):
            start = timezone.make_aware(start)
        now = timezone.now()
        if start > now:
            raise forms.ValidationError("Start date must be less "
                                        "or equal to now")
        if end and start >= end:
            raise forms.ValidationError("Start must be less "
                                        "than end date")
        return cleaned_data


class DistanceAverageSpeedTrainingForm(BaseTrainingForm):
    class Meta:
        fields = BaseTrainingForm.Meta.fields + ["average_speed", "distance"]


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields


class PowerTrainingForm(BaseTrainingForm):
    class Meta:
        model = PowerTraining
        fields = BaseTrainingForm.Meta.fields


class ExerciseForm(ModelForm):
    class Meta:
        model = Exercise
        fields = ["name", "description"]

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name", None)

        if (not self.instance.id
                and Exercise.objects.filter(name=name).exists()):
            raise forms.ValidationError("Exercise with this "
                                        "name already exists")

        return cleaned_data


class CyclingForm(DistanceAverageSpeedTrainingForm):
    description = forms.CharField(required=False)

    class Meta:
        model = Cycling
        fields = DistanceAverageSpeedTrainingForm.Meta.fields + ["climb"]

    def clean(self):
        cleaned_data = super(DistanceAverageSpeedTrainingForm, self).clean()
        climb = cleaned_data.get("climb", None)
        if not climb:
            raise forms.ValidationError("Climb is required field")
        if climb < 0:
            raise forms.ValidationError("Climb must be greater than zero")

        return cleaned_data


class DishForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DishForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Dish
        fields = ["name", "carbohydrates", "fats", "protein", "calories"]

    def clean(self):
        cleaned_data = super(DishForm, self).clean()

        protein = cleaned_data.get("protein", 0)
        carbohydrates = cleaned_data.get("carbohydrates", 0)
        fats = cleaned_data.get("fats", 0)

        if sum([protein, carbohydrates, fats]) >= 100:
            raise forms.ValidationError(
                "Sum of protein, carbohydrates "
                "and fats must be less than 100"
            )

        return cleaned_data


class CreateDishForm(DishForm):
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        Dish.validate_name(self.user, name, forms.ValidationError)


class UpdateDishForm(DishForm):
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")

        if self.instance.name == name:
            return

        Dish.validate_name(self.user, name, forms.ValidationError)


class JoggingForm(DistanceAverageSpeedTrainingForm):
    class Meta:
        model = Jogging
        fields = DistanceAverageSpeedTrainingForm.Meta.fields


class SwimmingForm(DistanceAverageSpeedTrainingForm):
    class Meta:
        model = Swimming
        fields = DistanceAverageSpeedTrainingForm.Meta.fields


class WalkingForm(DistanceAverageSpeedTrainingForm):
    class Meta:
        model = Walking
        fields = DistanceAverageSpeedTrainingForm.Meta.fields


class MealForm(ModelForm):
    class Meta:
        model = Meal
        fields = ["date"]


class DateSearchForm(forms.Form):
    choices = (
        ("DESC", "descending"),
        ("ASC", "ascending"),
    )
    start_date = forms.DateField(
        required=False,
    )
    end_date = forms.DateField(
        required=False,
    )
    sort = forms.ChoiceField(choices=choices, required=False)

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date", None)
        end_date = cleaned_data.get("end_date", None)

        if start_date and start_date > timezone.now().date():
            raise forms.ValidationError("Start date must be less "
                                        "or equal than now")
        if end_date and end_date > timezone.now().date():
            raise forms.ValidationError("End date must be less "
                                        "or equal than now")
        if end_date and start_date and start_date > end_date:
            raise forms.ValidationError("End date must be grater than "
                                        "start date")
        return cleaned_data


class NameSearchForm(forms.Form):
    choices = (
        ("DESC", "descending"),
        ("ASC", "ascending"),
    )
    name = forms.CharField(
        required=False,
        max_length=128,
    )
    sort = forms.ChoiceField(choices=choices, required=False)


class UserLoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False)

templates/main/meal/create-meal.html
{% extends "base.html" %}
{% block content %}
   <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body pt-3">
          <div class="row justify-content-center">
            <div class="col-lg-8">
              <form action="" method="post">
                {% if form.errors %}
                  {{ form.errors }}
                {% endif %}
                {% csrf_token %}
                <div class="row mb-3">
                  <label for="inputStartDate" class="col-md-3 col-lg-3 col-form-label text-center">
                    Date
                  </label>
                  <div class="col-md-9 col-lg-9">
                    <input type="datetime-local"
                           placeholder="dd/mm/yyyy H:M"
                           id="inputStartDate"
                           name="date"
                           class="form-control"
                           value="{% if default_date %}{{ default_date|date:"Y-m-d" }}T{{ default_date|time:"G:i" }}{% endif %}">
                  </div>
                </div>
                <div class="text-center">
                  <input type="submit" class="btn btn-primary" value="{% if object %}Update{% else %}Create{% endif %}">
                </div>
              </form>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>  
{% endblock %}

templates/main/meal/meal-list.html
{% extends "base.html" %}
{% block content %}
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-4">
        {% include "includes/date_search_form.html" %}
      </div>
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body">
            <div class="card-title-container">
              <h5 class="card-title">
                Meals
              </h5>
              <div class="d-flex h-50">
                <a href="{% url "main:create-meal" %}">
                  <i class="fa-solid fa-plus create-training-icon"></i>
                </a>
              </div>
            </div>
            <div class="meal-container row">
              {% for meal in meal_list%}
                <a href="{% url "main:update-meal" meal.id %}"
                   data-id="{{ meal.id }}"
                   class="col-lg-4">
                  <div class="alert alert-primary fade show">
                    <div class="d-flex justify-content-between">
                      <span>
                        {{ meal }}
                      </span>
                      <i class="fa-solid fa-xmark delete-element-icon delete-meal-icon"></i>
                    </div>
                  </div>
                </a>
              {% empty %}
                <h6 class="card-title">
                  No meals yet
                </h6>
              {% endfor %}
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/main/meal/update-meal.html
{% extends "base.html" %}
{% load tz %}
{% block content %}
  <div class="pagetitle">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url "main:meal-list" %}">Meals list</a>
        </li>
        <li class="breadcrumb-item">
          <a href="#">Update</a>
        </li>
      </ol>
    </nav>
  </div>
  <section class="section">
    <div class="row justify-content-center">
      <div class="col-lg-4">
        <div class="card">
          <div class="card-body pt3">
            <h5 class="card-title">
              Properties
            </h5>
            <form action="" method="post">
              {% if form.errors %}
                {{ form.errors }}
              {% endif %}
              {% csrf_token %}
              <div class="row mb-3">
                <label for="inputStartDate" class="col-md-3 col-lg-3 col-form-label text-center">
                  date
                </label>
                <div class="col-md-9 col-lg-9">
                  <input type="datetime-local"
                         placeholder="mm/dd/yyyy H:M:S"
                         id="inputStartDate"
                         name="date"
                         class="form-control"
                         value="{{ meal.date|date:"Y-m-d" }}T{{ meal.date|time:"G:i" }}">
                </div>
              </div>
              <div class="row mb-3">
                <label for="total_calories" class="col-md-3 col-lg-3 col-form-label text-center">
                  Calories
                </label>
                <div class="col-md-9 col-lg-9">
                  <input type="text"
                         id="total_calories"
                         class="form-control"
                         value="{{ meal.calories }}" disabled>
                </div>
              </div>
              <div class="row mb-3">
                <label for="total_fats" class="col-md-3 col-lg-3 col-form-label text-center">
                  Fats
                </label>
                <div class="col-md-9 col-lg-9">
                  <input type="text"
                         id="total_fats"
                         class="form-control"
                         value="{{ meal.fats }}" disabled>
                </div>
              </div>
              <div class="row mb-3">
                <label for="total_protein" class="col-md-3 col-lg-3 col-form-label text-center">
                  Protein
                </label>
                <div class="col-md-9 col-lg-9">
                  <input type="text"
                         id="total_protein"
                         class="form-control"
                         value="{{ meal.protein }}" disabled>
                </div>
              </div>
            <div class="row mb-3">
                <label for="total_carbohydrates" class="col-md-3 col-lg-3 col-form-label text-center">
                  Carbohydrates
                </label>
                <div class="col-md-9 col-lg-9">
                  <input type="text"
                         id="total_carbohydrates"
                         class="form-control"
                         value="{{ meal.carbohydrates }}" disabled>
                </div>
              </div>
              <div class="text-center">
                <input class="btn btn-success" type="submit" value="update"/>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card">
          <div class="card-body gap-3" id="card_update_power_training">
            <div class="card-title-container mb-3">
              <h5 class="card-title">
                Dishes
              </h5>
              <div class="card-title-container gap-3">
                <select class="form-select" id="select_dish">
                  {% for dish in user.dishes.all %}
                    <option value="{{ dish.id }}">{{ dish.name }}</option>
                  {% empty %}
                    <option value="-1">No dishes yet</option>
                  {% endfor %}
                </select>
                <i id="addDish" class="fa-solid fa-plus create-training-icon"></i>
              </div>
            </div>
            <ul class="list-group mb-3"  id="meal_list_group">
              {% for dish_count in meal.dishes.all %}
                <li class="list-group-item" data-dish-count-id="{{ dish_count.id }}" data-dish-id="{{ dish_count.dish.id }}">
                  <div class="d-flex">
                    <div class="card-title-container gap-2 justify-content-between">
                      <input type="text"
                             class="form-control"
                             value="{{ dish_count.dish.name }}"
                             disabled>
                      <span>Weight</span>
                      <input type="number"
                             class="form-control weightInput"
                             name="weight"
                             value="{{ dish_count.weight }}"/>
                      <button class="btn btn-primary create-or-update-dish-count">Update</button>
                      <i class="bi bi-x-circle-fill deleteDishCount deleteIcon"></i>
                    </div>
                  </div>
                </li>
              {% empty %}
                <h6 class="card-title" id="no-dish-message">
                  No dishes yet
                </h6>
              {% endfor %}
            </ul>
            <input type="hidden" value="{{ meal.id }}" id="meal_id">
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}