app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("api/", include("ajax.urls", namespace="api")),
    path("api/user/", include("user.urls", namespace="user")),
]

main/urls.py
from django.urls import path

from main.views import (
    CreateCyclingTrainingView,
    CreateDishView,
    CreateJoggingView,
    CreateMealView,
    CreatePowerTrainingView,
    CreateSwimmingView,
    CreateUserView,
    CreateWalkingView,
    CyclingTrainingListView,
    DishListView,
    ExerciseCreateView,
    ExercisesListView,
    ExerciseUpdateView,
    HomePageView,
    JoggingTrainingListView,
    LoginUserView,
    MealListView,
    PowerTrainingsListView,
    SwimmingTrainingListView,
    UpdateCyclingTrainingView,
    UpdateDishView,
    UpdateJoggingView,
    UpdateMealView,
    UpdatePowerTrainingView,
    UpdateSwimmingView,
    UpdateWalkingView,
    UserProfileView,
    WalkingTrainingListView,
    logout_view,
)


urlpatterns = [
    path(
        "",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "home/",
        HomePageView.as_view(),
        name="home"
    ),
    path(
        "power-trainings/",
        PowerTrainingsListView.as_view(),
        name="power-trainings-list",
    ),
    path(
        "power-trainings/create",
        CreatePowerTrainingView.as_view(),
        name="create-power-training",
    ),
    path(
        "account/registration",
        CreateUserView.as_view(),
        name="registration"
    ),
    path(
        "accounts/login",
        LoginUserView.as_view(),
        name="login"
    ),
    path(
        "accounts/logout",
        logout_view,
        name="logout"
    ),
    path(
        "accounts/user-profile",
        UserProfileView.as_view(),
        name="user-profile"
    ),
    path(
        "exercises/",
        ExercisesListView.as_view(),
        name="exercises-list"
    ),
    path(
        "exercise/<int:pk>",
        ExerciseUpdateView.as_view(),
        name="exercise-update"
    ),
    path(
        "exercises/create/",
        ExerciseCreateView.as_view(),
        name="create-exercise"
    ),
    path(
        "power-trainings/update/<int:pk>",
        UpdatePowerTrainingView.as_view(),
        name="update-power-training",
    ),
    path(
        "cycling-trainings/",
        CyclingTrainingListView.as_view(),
        name="cycling-training-list",
    ),
    path(
        "cycling-trainings/create",
        CreateCyclingTrainingView.as_view(),
        name="create-cycling-training",
    ),
    path(
        "cycling-trainings/update/<int:pk>",
        UpdateCyclingTrainingView.as_view(),
        name="update-cycling-training",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/create",
        CreateDishView.as_view(),
        name="create-dish"
    ),
    path(
        "dishes/update/<int:pk>",
        UpdateDishView.as_view(),
        name="update-dish"
    ),
    path(
        "swimming-trainings/",
        SwimmingTrainingListView.as_view(),
        name="swimming-training-list",
    ),
    path(
        "walking-trainings/",
        WalkingTrainingListView.as_view(),
        name="walking-training-list",
    ),
    path(
        "jogging-trainings/",
        JoggingTrainingListView.as_view(),
        name="jogging-training-list",
    ),
    path(
        "swimming-trainings/create",
        CreateSwimmingView.as_view(),
        name="create-swimming-training",
    ),
    path(
        "walking-trainings/create",
        CreateWalkingView.as_view(),
        name="create-walking-training",
    ),
    path(
        "jogging-traings/create",
        CreateJoggingView.as_view(),
        name="create-jogging-training",
    ),
    path(
        "swimming-trainings/update/<int:pk>",
        UpdateSwimmingView.as_view(),
        name="update-swimming-training",
    ),
    path(
        "jogging-traings/update/<int:pk>",
        UpdateJoggingView.as_view(),
        name="update-jogging-training",
    ),
    path(
        "walking-trainings/update/<int:pk>",
        UpdateWalkingView.as_view(),
        name="update-walking-training",
    ),
    path(
        "meals/",
        MealListView.as_view(),
        name="meal-list"
    ),
    path(
        "meals/create",
        CreateMealView.as_view(),
        name="create-meal"
    ),
    path(
        "meals/update/<int:pk>",
        UpdateMealView.as_view(),
        name="update-meal"
    ),
]

app_name = "main"

templates/main/trainings/cycling_training/cycling-training-form.html
{% extends "base_distance_average_speed_form.html" %}
{% block AdditionalFields %}
  <div class="row mb-3">
    <label for="inputClimb" class="col-md-3 col-lg-3 col-form-label text-center">
      climb
    </label>
    <div class="col-md-9 col-lg-9">
      <input type="number"
             id="inputClimb"
             name="climb"
             class="form-control"
             placeholder="m"
             value="{% if object %}{{ object.climb }}{% endif %}">
    </div>

  </div>
  <input type="hidden" name="next" value="{% url "main:cycling-training-list" %}">
{% endblock %}

templates/main/trainings/cycling_training/cycling-training-list.html
{% extends "base_training_list.html" %}
{% block title %}Cycling trainings{% endblock %}
{% block create_url %}{% url "main:create-cycling-training" %}{% endblock %}
{% block trainings %}
  {% for cycling in cycling_list%}
    <a href="{% url "main:update-cycling-training" cycling.id %}"
       class="training-element col-lg-4"
       data-training-id="{{ cycling.id }}"
       data-training-type="CY">
      <div class="alert alert-primary fade show">
        <div class="d-flex justify-content-between">
          <span>
             {{ cycling }}
          </span>
          <i class="fa-solid fa-xmark delete-element-icon delete-training-icon"></i>
        </div>
      </div>
    </a>
  {% empty %}
    <h6 class="card-title">
      No trainings yet
    </h6>
  {% endfor %}
{% endblock %}